name: storybook

networks:
  storybook:
    driver: bridge

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      - server
      - mariadb
    networks:
      - storybook
    ports:
      - 3000:3000
    restart: always
  server:
    build:
      context: server
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - storybook
    ports:
      - 8080:8080
    restart: always
  mariadb:
    image: mariadb:11
    container_name: mariadb
    volumes:
      - db-data:/var/lib/mysql  # 使用命名卷持久化 MySQL 数据
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=storybook
      - MYSQL_USER=storybook
      - MYSQL_PASSWORD=storybook123
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    networks:
      - storybook
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 1m
      interval: 30s
      timeout: 5s
      retries: 3
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"  # HTTP 端口
    networks:
      - storybook
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf  # 挂载 Nginx 配置文件
      - ./proxy/certs/:/etc/nginx/certs            # 挂载 SSL 证书
    restart: always

volumes:
  db-data:




